name: pretty
version: 0.0.5
author: Paul Brauner <polux@google.com>
description: A sample command-line application
homepage: https://github.com/polux/pretty
dev_dependencies:
  persistent: any
  unittest: any
